2025-04-16 23:40:57,821 - INFO - Subscriber is listening for messages.
2025-04-16 23:42:01,682 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 26, in callback
    data = json.loads(message.data.decode("utf-8"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2025-04-16 23:51:31,216 - INFO - Subscriber is listening for messages.
2025-04-17 16:45:08,128 - INFO - Subscriber is listening for messages.
2025-04-17 16:45:09,549 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-17 16:45:09,666 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-17 16:45:09,807 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-17 16:45:09,920 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-17 16:45:09,999 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 21, in is_duplicate
    cursor.execute("SELECT COUNT(*) FROM messages WHERE message_id = %s", (message_id,))
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 763, in _read_packet
    recv_data = self._read_bytes(bytes_to_read)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 782, in _read_bytes
    data = self._rfile.read(num_bytes)
           ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'read'
2025-04-17 16:45:10,000 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 21, in is_duplicate
    cursor.execute("SELECT COUNT(*) FROM messages WHERE message_id = %s", (message_id,))
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 753, in _read_packet
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
2025-04-17 16:45:10,061 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 26, in callback
    data = json.loads(message.data.decode("utf-8"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2025-04-17 16:45:10,144 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 21, in is_duplicate
    cursor.execute("SELECT COUNT(*) FROM messages WHERE message_id = %s", (message_id,))
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 562, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 843, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')
2025-04-17 16:45:10,251 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 21, in is_duplicate
    cursor.execute("SELECT COUNT(*) FROM messages WHERE message_id = %s", (message_id,))
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 562, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 843, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')
2025-04-17 16:45:10,371 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 26, in callback
    data = json.loads(message.data.decode("utf-8"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2025-04-17 16:45:10,541 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 21, in is_duplicate
    cursor.execute("SELECT COUNT(*) FROM messages WHERE message_id = %s", (message_id,))
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 562, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 843, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')
2025-04-17 16:45:10,736 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samanthajulian/Documents/GitHub/Cloud-Messaging/subscription.py", line 21, in is_duplicate
    cursor.execute("SELECT COUNT(*) FROM messages WHERE message_id = %s", (message_id,))
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 562, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/opt/anaconda3/lib/python3.12/site-packages/pymysql/connections.py", line 843, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')
2025-04-17 17:56:05,956 - INFO - Subscriber is listening for messages.
2025-04-17 18:15:07,862 - INFO - Subscriber is listening for messages.
2025-04-17 18:17:24,957 - INFO - Subscriber is listening for messages.
2025-04-17 18:18:37,704 - INFO - Subscriber is listening for messages.
2025-04-17 18:19:21,706 - INFO - Subscriber is listening for messages.
