2025-04-16 23:40:57,821 - INFO - Subscriber is listening for messages.
2025-04-16 23:42:01,682 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 26, in callback
    data = json.loads(message.data.decode("utf-8"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2025-04-16 23:51:31,216 - INFO - Subscriber is listening for messages.
2025-04-17 18:11:03,787 - INFO - Subscriber is listening for messages.
2025-04-17 18:41:25,667 - INFO - Subscriber is listening for messages.
2025-04-17 18:43:39,765 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/karendonjuan/Desktop/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karendonjuan/Desktop/Cloud-Messaging/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-17 18:43:44,521 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/karendonjuan/Desktop/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karendonjuan/Desktop/Cloud-Messaging/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-17 18:43:49,052 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/karendonjuan/Desktop/Cloud-Messaging/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karendonjuan/Desktop/Cloud-Messaging/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-17 18:48:51,133 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/karendonjuan/Desktop/Cloud-Messaging/subscription.py", line 26, in callback
    data = json.loads(message.data.decode("utf-8"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2025-04-21 19:11:52,939 - INFO - Subscriber is listening for messages.
2025-04-21 19:11:55,227 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 26, in callback
    data = json.loads(message.data.decode("utf-8"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2025-04-21 19:36:12,598 - INFO - Subscriber is listening for messages.
2025-04-21 20:42:58,261 - INFO - Subscriber is listening for messages.
2025-04-21 20:57:58,313 - INFO - Re-established stream
2025-04-21 21:12:58,350 - INFO - Re-established stream
2025-04-21 21:19:15,082 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-21 21:20:55,114 - INFO - Subscriber is listening for messages.
2025-04-21 21:21:36,751 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-21 21:22:02,266 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-21 21:23:20,618 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-21 21:24:51,512 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-21 21:25:06,528 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-21 21:27:36,808 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 37, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 22, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2025-04-21 21:35:55,161 - INFO - Re-established stream
2025-04-21 21:39:27,381 - ERROR - Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 37, in callback
    data.get("Location"),
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 22, in is_duplicate
    status = data.get("Status", "UNKNOWN")
       ^^^^^^^^^^^^^^^^^^^^
KeyError: 0
ERROR:root:❌ Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 30, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 15, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
ERROR:root:❌ Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 30, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 15, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
ERROR:root:❌ Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 30, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 15, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
ERROR:root:❌ Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 30, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 15, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
ERROR:root:❌ Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 30, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 15, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
ERROR:root:❌ Error processing message
Traceback (most recent call last):
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 30, in callback
    if not is_duplicate(message_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lane/Documents/GitHub/IS_Capstone/subscription.py", line 15, in is_duplicate
    return cursor.fetchone()[0] > 0
           ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
INFO:google.api_core.bidi:Thread-ConsumeBidirectionalStream exiting
INFO:google.api_core.bidi:Thread-ConsumeBidirectionalStream exiting
INFO:google.api_core.bidi:Thread-ConsumeBidirectionalStream exiting
INFO:google.api_core.bidi:Thread-ConsumeBidirectionalStream exiting
INFO:google.api_core.bidi:Re-established stream
INFO:google.api_core.bidi:Thread-ConsumeBidirectionalStream exiting
INFO:google.api_core.bidi:Re-established stream
INFO:google.api_core.bidi:Re-established stream
INFO:google.api_core.bidi:Thread-ConsumeBidirectionalStream exiting
INFO:google.api_core.bidi:Thread-ConsumeBidirectionalStream exiting
